from config import WeaponStatsConfig


autocannon = WeaponStatsConfig(name='Autocannon', base_dice=3, base_edice=0, a_pen=0, auto=2, stat_mod='reflex', weapon_range=8, svg=360, rsc=7)
ciws_advanced = WeaponStatsConfig(name='CIWS, Advanced', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='reflex', weapon_range=1, svg=720, rsc=1)
ciws = WeaponStatsConfig(name='CIWS', base_dice=0, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=1, svg=400, rsc=1)
autocannon_anti_infantry = WeaponStatsConfig(name='Autocannon, Anti-Infantry', base_dice=-1, base_edice=0, a_pen=0, auto=2, stat_mod='reflex',  weapon_range=3, svg=60, rsc=4)
battle_cannon = WeaponStatsConfig(name='Battle Cannon', base_dice=3, base_edice=2, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=18, svg=600, rsc=12)
autocannon_heavy = WeaponStatsConfig(name='Autocannon, Heavy', base_dice=2, base_edice=2, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=10, svg=440, rsc=8)
artillery_rifle_heavy = WeaponStatsConfig(name='Artillery Rifle, Heavy', base_dice=9, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=60, svg=1000, rsc=36)
battle_cannon_heavy = WeaponStatsConfig(name='Battle Cannon, Heavy', base_dice=4, base_edice=3, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=22, svg=800, rsc=18)
machine_gun_heavy = WeaponStatsConfig(name='Machine Gun, Heavy', base_dice=-1, base_edice=0, a_pen=0, auto=4, stat_mod='reflex',  weapon_range=4, svg=120, rsc=5)
autocannon_light = WeaponStatsConfig(name='Autocannon, Light', base_dice=2, base_edice=0, a_pen=0, auto=2, stat_mod='reflex',  weapon_range=6, svg=240, rsc=5)
artillery_rifle_light = WeaponStatsConfig(name='Artillery Rifle, Light', base_dice=6, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=40, svg=800, rsc=24)
machine_gun_light = WeaponStatsConfig(name='Machine Gun, Light', base_dice=1, base_edice=0, a_pen=0, auto=3, stat_mod='none',  weapon_range=2, svg=40, rsc=2)
rotary_autocannon_light = WeaponStatsConfig(name='Rotary Autocannon, Light', base_dice=0, base_edice=0, a_pen=0, auto=3, stat_mod='reflex',  weapon_range=6, svg=270, rsc=4)
magnetic_anti_material_rifle = WeaponStatsConfig(name='Magnetic Anti-Material Rifle', base_dice=6, base_edice=0, a_pen=5, auto=0, stat_mod='reflex',  weapon_range=8, svg=860, rsc=10)
magnetic_auto_rifle = WeaponStatsConfig(name='Magnetic Auto-Rifle', base_dice=1, base_edice=0, a_pen=1, auto=3, stat_mod='reflex',  weapon_range=8, svg=300, rsc=3)
magnetic_sniper_rifle = WeaponStatsConfig(name='Magnetic Sniper Rifle', base_dice=3, base_edice=0, a_pen=3, auto=2, stat_mod='reflex',  weapon_range=10, svg=540, rsc=5)
rotary_autocannon = WeaponStatsConfig(name='Rotary Autocannon', base_dice=1, base_edice=0, a_pen=0, auto=3, stat_mod='reflex',  weapon_range=6, svg=320, rsc=9)
recoilless_rifle = WeaponStatsConfig(name='Recoilless Rifle', base_dice=0, base_edice=2, a_pen=0, auto=0, stat_mod='none',  weapon_range=5, svg=80, rsc=5)
high_energy_laser_focused = WeaponStatsConfig(name='High Energy Laser, Focused', base_dice=6, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=40, svg=700, rsc=3)
high_energy_laser = WeaponStatsConfig(name='High Energy Laser', base_dice=5, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=24, svg=500, rsc=2)
low_power_laser = WeaponStatsConfig(name='Low Power Laser', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=20, svg=180, rsc=1)
plasma_blaster = WeaponStatsConfig(name='Plasma Blaster', base_dice=0, base_edice=3, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=2, svg=520, rsc=8)
plasma_lance = WeaponStatsConfig(name='Plasma Lance', base_dice=2, base_edice=0, a_pen=8, auto=0, stat_mod='reflex',  weapon_range=6, svg=600, rsc=8)
rapid_fire_laser = WeaponStatsConfig(name='Rapid Fire Laser', base_dice=0, base_edice=0, a_pen=0, auto=4, stat_mod='reflex',  weapon_range=16, svg=300, rsc=1)
twin_laser = WeaponStatsConfig(name='Twin Laser', base_dice=2, base_edice=0, a_pen=0, auto=2, stat_mod='reflex',  weapon_range=20, svg=400, rsc=1)
arc_mace = WeaponStatsConfig(name='Arc-Mace', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=260, rsc=1)
dagger = WeaponStatsConfig(name='Dagger', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='reflex',  weapon_range=1, svg=40, rsc=0)
hammer = WeaponStatsConfig(name='Hammer', base_dice=7, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=200, rsc=0)
rocket_hammer = WeaponStatsConfig(name='Rocket Hammer', base_dice=12, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=380, rsc=1)
sword = WeaponStatsConfig(name='Sword', base_dice=5, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=120, rsc=0)
axe = WeaponStatsConfig(name='Axe', base_dice=5, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=120, rsc=0)
heavy_missiles_emp = WeaponStatsConfig(name='Heavy Missiles, EMP', base_dice=0, base_edice=4, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=15, svg=350, rsc=45)
heavy_missiles_kinetic = WeaponStatsConfig(name='Heavy Missiles, Kinetic', base_dice=8, base_edice=0, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=12, svg=350, rsc=30)
heavy_missiles = WeaponStatsConfig(name='Heavy Missiles', base_dice=0, base_edice=6, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=15, svg=350, rsc=40)
heavy_missiles_plasma = WeaponStatsConfig(name='Heavy Missiles, Plasma', base_dice=0, base_edice=10, a_pen=3, auto=0, stat_mod='intellect',  weapon_range=15, svg=520, rsc=60)
heavy_missiles_swarm = WeaponStatsConfig(name='Heavy Missiles, Swarm', base_dice=0, base_edice=3, a_pen=0, auto=3, stat_mod='intellect',  weapon_range=15, svg=350, rsc=14)
rocket_pod_light = WeaponStatsConfig(name='Rocket Pod, Light', base_dice=0, base_edice=1, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=5, svg=160, rsc=8)
rocket_pod_ripple = WeaponStatsConfig(name='Rocket Pod, Ripple', base_dice=0, base_edice=1, a_pen=0, auto=3, stat_mod='intellect',  weapon_range=4, svg=280, rsc=8)
rocket_pod = WeaponStatsConfig(name='Rocket Pod', base_dice=0, base_edice=3, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=6, svg=220, rsc=10)
standard_missiles_emp = WeaponStatsConfig(name='Standard Missiles, EMP', base_dice=0, base_edice=3, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=12, svg=200, rsc=26)
standard_missiles_kinetic = WeaponStatsConfig(name='Standard Missiles, Kinetic', base_dice=5, base_edice=0, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=12, svg=200, rsc=18)
standard_missiles = WeaponStatsConfig(name='Standard Missiles', base_dice=0, base_edice=4, a_pen=0, auto=0, stat_mod='intellect',  weapon_range=12, svg=200, rsc=24)
standard_missiles_plasma = WeaponStatsConfig(name='Standard Missiles, Plasma', base_dice=0, base_edice=6, a_pen=3, auto=0, stat_mod='intellect',  weapon_range=12, svg=300, rsc=36)
standard_missiles_swarm = WeaponStatsConfig(name='Standard Missiles, Swarm', base_dice=0, base_edice=2, a_pen=0, auto=3, stat_mod='intellect',  weapon_range=12, svg=200, rsc=8)
claws_large = WeaponStatsConfig(name='Claws, Large', base_dice=3, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=50, rsc=0)
claws_small = WeaponStatsConfig(name='Claws, Small', base_dice=1, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=20, rsc=0)
claws_standard = WeaponStatsConfig(name='Claws, Standard', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=30, rsc=0)
hand_large = WeaponStatsConfig(name='Hand, Large', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=110, rsc=0)
hand_small = WeaponStatsConfig(name='Hand, Small', base_dice=0, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=60, rsc=0)
hand_standard = WeaponStatsConfig(name='Hand, Standard', base_dice=1, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=80, rsc=0)
scissors_large = WeaponStatsConfig(name='Scissors, Large', base_dice=4, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=90, rsc=0)
scissors_small = WeaponStatsConfig(name='Scissors, Small', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=50, rsc=0)
scissors_standard = WeaponStatsConfig(name='Scissors, Standard', base_dice=3, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=70, rsc=0)
shield_basic = WeaponStatsConfig(name='Shield, Basic', base_dice=2, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=120, rsc=0)
shield_buckler = WeaponStatsConfig(name='Shield, Buckler', base_dice=-1, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=50, rsc=0)
shield_heavy = WeaponStatsConfig(name='Shield, Heavy', base_dice=3, base_edice=0, a_pen=0, auto=0, stat_mod='endurance',  weapon_range=1, svg=200, rsc=0)
